version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        container_name: symfony_php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            APP_ENV: dev
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:15
        container_name: symfony_db
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/postgresql/data

    node:
        image: node:20
        container_name: symfony_node
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: tail -f /dev/null # możesz zmienić np. na "npm run dev"

volumes:
    db_data:
