version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        container_name: symfony_php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            APP_ENV: dev
        depends_on:
            - db
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - node
        networks:
            - app-network

    db:
        image: postgres:15
        container_name: symfony_db
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

    node:
        image: node:20
        container_name: symfony_node
        working_dir: /app
        volumes:
            - ./strapi-cms:/app
        command:  sh -c "npm install && npm run develop"
        environment:
            - HOST=0.0.0.0
            - PORT=1337
        ports:
            - "1337:1337"
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
