<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN4Dn0oF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN4Dn0oF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN4Dn0oF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN4Dn0oF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN4Dn0oF\App_KernelDevDebugContainer([
    'container.build_hash' => 'N4Dn0oF',
    'container.build_id' => '480c483a',
    'container.build_time' => 1749311363,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN4Dn0oF');
