<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYw7mxX3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYw7mxX3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYw7mxX3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYw7mxX3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYw7mxX3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yw7mxX3',
    'container.build_id' => 'c1776e4b',
    'container.build_time' => 1749315274,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYw7mxX3');
